using iSlideAddIn.Dialogs;
namespace iSlideAddIn;
public static class ImageExportManager
{
    public static void ShowExportDialog() { if (AddInModule.PowerPointApp?.ActivePresentation == null) return; using var d = new ExportDialog(false); if (d.ShowDialog() != System.Windows.Forms.DialogResult.OK) return; ExportImages(d.OutputPath, d.Format, d.Dpi, d.SelectedSlides); }
    public static void ShowLongImageDialog() { if (AddInModule.PowerPointApp?.ActivePresentation == null) return; using var d = new ExportDialog(true); if (d.ShowDialog() != System.Windows.Forms.DialogResult.OK) return; ExportLongImage(d.OutputPath, d.Dpi, d.SelectedSlides); }
    public static void ExportImages(string dir, string fmt, int dpi, List<int> slides) { var a = AddInModule.PowerPointApp; if (a?.ActivePresentation == null) return; dynamic pres = a.ActivePresentation; float sc = dpi / 72f, pw = pres.PageSetup.SlideWidth, ph = pres.PageSetup.SlideHeight; Directory.CreateDirectory(dir); int c = 0; foreach (int i in slides) { pres.Slides[i].Export(Path.Combine(dir, $"slide_{i:D3}.{fmt.ToLower()}"), fmt.ToUpper(), (int)(pw * sc), (int)(ph * sc)); c++; } M($"Exported {c} slides."); }
    public static void ExportLongImage(string op, int dpi, List<int> slides) { var a = AddInModule.PowerPointApp; if (a?.ActivePresentation == null) return; dynamic pres = a.ActivePresentation; float sc = dpi / 72f, pw = pres.PageSetup.SlideWidth, ph = pres.PageSetup.SlideHeight; int iw = (int)(pw * sc), ih = (int)(ph * sc); string tmp = Path.Combine(Path.GetTempPath(), "islide_li"); Directory.CreateDirectory(tmp); try { var imgs = new List<System.Drawing.Bitmap>(); foreach (int i in slides) { string tp = Path.Combine(tmp, $"t_{i}.png"); pres.Slides[i].Export(tp, "PNG", iw, ih); imgs.Add(new System.Drawing.Bitmap(tp)); File.Delete(tp); } int mw = 0, th = 0; foreach (var img in imgs) { mw = Math.Max(mw, img.Width); th += img.Height; } th += 10 * (imgs.Count - 1); using var res = new System.Drawing.Bitmap(mw, th); using var g = System.Drawing.Graphics.FromImage(res); g.Clear(System.Drawing.Color.White); int y = 0; foreach (var img in imgs) { g.DrawImage(img, (mw - img.Width) / 2, y); y += img.Height + 10; img.Dispose(); } var f = Path.GetExtension(op).ToLower() is ".jpg" or ".jpeg" ? System.Drawing.Imaging.ImageFormat.Jpeg : System.Drawing.Imaging.ImageFormat.Png; res.Save(op, f); M($"Saved long image."); } finally { try { Directory.Delete(tmp, true); } catch { } } }
    static void M(string m) => System.Windows.Forms.MessageBox.Show(m, "iSlide", System.Windows.Forms.MessageBoxButtons.OK, System.Windows.Forms.MessageBoxIcon.Information);
}
